### ISSUE TITLE
User player lacks permision to create a new ActiveEffect

### ISSUE THREAD

**Issue by jesucar3** [scottburton11/burger-time#3]
![Captura](https://user-images.githubusercontent.com/86451488/123359093-a223b280-d53a-11eb-8d04-7464d4e5738e.PNG)
after the first meal this happen

**Comment by jesucar3** [comment]
using 0.8.7 version of this, and dae

**Comment by jesucar3** [comment]
bug

**Comment by aprusik** [comment]
I am also getting this error, on 0.8.8 with only About Time, SmallTime, Simple Calender, and Burger Time installed. It also seems that eating rations does not reset the hours since eating after looking at the Hunger Table. Also, no effect appears on the actor.

**Comment by scottburton11** [comment]
Thanks for the report @jesucar3 and @aprusik:

* Eating does not reset - this should be fixed in an upcoming release shortly
* No effect appears on the actor/user lacks permission - having a hard time duplicating this.  Can you please share the Player Permission settings for that actor? Is it "Owner" or something else?
 
![image](https://user-images.githubusercontent.com/12917/123559331-39158800-d750-11eb-8f10-52bacd3f5a89.png)

**Comment by jesucar3** [comment]
the hunger starts/restarts when you f5 the foundry (in localhost), the player has owner and every permission that i can give it in permission configuration, and i have libwrapper

https://user-images.githubusercontent.com/86451488/123564905-266b7500-d789-11eb-8eb7-797fe3b76445.mp4

i hope this will be usefull, thx for this great addon

**Comment by scottburton11** [comment]
Got it, thanks for the video @jesucar3 - I'm still investigating. According to Kandashi, it could be "Create New Items" permission or the "Use Script Macros" permission under User Management > Configure Permissions.

Will investigate further.

**Comment by jesucar3** [comment]
hi, when i sended the video the players already had that permission (i give all the permissions in user management)
thanks and have a nice day

**Comment by scottburton11** [comment]
Hey @jesucar3 - 

I haven't released a new version yet, but this change should eliminate any permissions issues with players. The behavior is still the same otherwise. I should be releasing an updated version soon, but please feel free to test it out in the meantime: 

https://github.com/scottburton11/burger-time/commit/bda2383699cdb9d5f1ff35d85698d85a4ed3ebc3

**Comment by scottburton11** [comment]
@jesucar3 I just released https://github.com/scottburton11/burger-time/releases/tag/0.1.8 - please give it a try

**Comment by scottburton11** [comment]
@jesucar3 thanks again for reporting, I think this is fixed in 0.1.8 and beyond, so I'm closing this for now. Please feel free to reopen or report any other issue you encounter!
